[package]
name = "layer-conform"
description = "Detect style deviations within an architectural layer of TS/JS/Rust projects."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords = ["lint", "architecture", "ddd", "cli", "similarity"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "layer-conform"
path = "src/main.rs"

[dependencies]
layer-conform-core.workspace = true
layer-conform-io.workspace = true
layer-conform-ts.workspace = true
layer-conform-rs.workspace = true
clap.workspace = true
anyhow.workspace = true
compact_str.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[lints]
workspace = true

[badges]
maintenance = { status = "experimental" }
